// generated by tools/gen_assets.py -- do not edit
#pragma once
#include "gfx.h"

extern const sprite_t SPR_PLAYER;
extern const sprite_t SPR_PLAYER_UP;
extern const sprite_t SPR_PLAYER_DN;
extern const sprite_t SPR_DRONE;
extern const sprite_t SPR_DARTER;
extern const sprite_t SPR_FIGHTER;
extern const sprite_t SPR_POD;
extern const sprite_t SPR_MINE;
extern const sprite_t SPR_ROCK_L;
extern const sprite_t SPR_ROCK_M;
extern const sprite_t SPR_ROCK_S;
extern const sprite_t SPR_GUNSHIP;
extern const sprite_t SPR_CARRIER;
extern const sprite_t SPR_SPINNER;
extern const sprite_t SPR_WEAVER;
extern const sprite_t SPR_JELLY;
extern const sprite_t SPR_TURRET;
extern const sprite_t SPR_EYE;
extern const sprite_t SPR_SEEKER;
extern const sprite_t SPR_CARGO;
extern const sprite_t SPR_LOGO;
extern const sprite_t SPR_PLANET_ICE;
extern const sprite_t SPR_GLACIER;
extern const sprite_t SPR_SHARD;
extern const sprite_t SPR_HYDRA_HEAD;
extern const sprite_t SPR_HYDRA_SEG;
extern const sprite_t SPR_SATELLITE;
extern const sprite_t SPR_SHOT_PULSE;
extern const sprite_t SPR_SHOT_SPREAD;
extern const sprite_t SPR_MISSILE;
extern const sprite_t SPR_EB_S_PINK;
extern const sprite_t SPR_EB_M_PINK;
extern const sprite_t SPR_EB_L_PINK;
extern const sprite_t SPR_EB_S_ORNG;
extern const sprite_t SPR_EB_M_ORNG;
extern const sprite_t SPR_EB_S_BLUE;
extern const sprite_t SPR_EB_M_BLUE;
extern const sprite_t SPR_EB_NEEDLE;
extern const sprite_t SPR_CAP_RED;
extern const sprite_t SPR_CAP_BLUE;
extern const sprite_t SPR_CAP_GREEN;
extern const sprite_t SPR_CAP_GOLD;
extern const sprite_t SPR_CAP_VIOLET;
extern const sprite_t SPR_GEM0;
extern const sprite_t SPR_GEM1;
extern const sprite_t SPR_GEM2;
extern const sprite_t SPR_GEM3;
extern const sprite_t SPR_FIRE0;
extern const sprite_t SPR_FIRE1;
extern const sprite_t SPR_FIRE2;
extern const sprite_t SPR_FIRE3;
extern const sprite_t SPR_FIRE4;
extern const sprite_t SPR_FIRE5;
extern const sprite_t SPR_FIRE6;
extern const sprite_t SPR_FIRE7;
extern const sprite_t SPR_SMOKE0;
extern const sprite_t SPR_SMOKE1;
extern const sprite_t SPR_SMOKE2;
extern const sprite_t SPR_SMOKE3;
extern const sprite_t SPR_SMOKE4;
extern const sprite_t SPR_SMOKE5;
extern const sprite_t SPR_ICON_SHIP;
extern const sprite_t SPR_ICON_BOMB;
extern const sprite_t *const ANIM_GEM[4];
#define ANIM_GEM_N 4
extern const sprite_t *const ANIM_FIRE[8];
#define ANIM_FIRE_N 8
extern const sprite_t *const ANIM_SMOKE[6];
#define ANIM_SMOKE_N 6
