// generated by tools/gen_pacman.py -- do not edit
#pragma once
#include <stdint.h>

#define PAC_MAZES   3
#define PM_W        38
#define PM_H        27
#define PAC_TILE_N  186
#define PAC_MINI_N  132

// a 4-bit brightness image, two pixels a byte, high nibble first
typedef struct { uint16_t w, h; const uint8_t *pix; } pac_image_t;

extern const char PAC_MAZE[PAC_MAZES][PM_H][PM_W + 1];
extern const uint8_t PAC_TILES[PAC_TILE_N][32];
extern const uint16_t PAC_TILEMAP[PAC_MAZES][PM_H][PM_W];
extern const uint8_t PAC_MINI_TILES[PAC_MINI_N][8];
extern const uint8_t PAC_MINI_MAP[PAC_MAZES][PM_H][PM_W];
extern const pac_image_t PAC_LOGO_BIG, PAC_LOGO_SMALL;
