#!/usr/bin/env python3
#
# QUASAR - builds game/assets_gen.c and game/assets_gen.h
#
# All art is either hand drawn below as text, or generated procedurally. Run:
#
#     python3 tools/gen_assets.py [--preview sheet.png]
#
import sys, os, math, random, argparse
sys.path.insert(0, os.path.dirname(__file__))
from artlib import *
import sprites

def emit(out_c, out_h, sprites_list, anims):
    lines = ['// generated by tools/gen_assets.py -- do not edit', '#include "assets_gen.h"', '']
    hdr = ['// generated by tools/gen_assets.py -- do not edit', '#pragma once',
           '#include "gfx.h"', '']

    pal_ids = {}
    pal_defs = []
    total = 0
    for name, img, ox, oy in sprites_list:
        idx, pal = quantize(img)
        key = tuple(pal)
        if key not in pal_ids:
            pid = 'pal_%d' % len(pal_ids)
            pal_ids[key] = pid
            pal_defs.append('static const px_t %s[%d] = { %s };' % (
                pid, len(pal), ', '.join('0x%04x' % swap16(v) for v in pal)))
        flat = [v for row in idx for v in row]
        total += len(flat)
        lines.append('static const uint8_t pix_%s[%d] = {' % (name.lower(), len(flat)))
        for i in range(0, len(flat), 32):
            lines.append('    ' + ','.join(str(v) for v in flat[i:i + 32]) + ',')
        lines.append('};')
        hdr.append('extern const sprite_t SPR_%s;' % name.upper())

    body = []
    for name, img, ox, oy in sprites_list:
        idx, pal = quantize(img)
        body.append('const sprite_t SPR_%s = { %d, %d, %d, %d, pix_%s, %s };' % (
            name.upper(), img.w, img.h, ox, oy, name.lower(), pal_ids[tuple(pal)]))

    anim_lines = []
    for aname, frames in anims:
        hdr.append('extern const sprite_t *const ANIM_%s[%d];' % (aname.upper(), len(frames)))
        hdr.append('#define ANIM_%s_N %d' % (aname.upper(), len(frames)))
        anim_lines.append('const sprite_t *const ANIM_%s[%d] = { %s };' % (
            aname.upper(), len(frames), ', '.join('&SPR_%s' % f.upper() for f in frames)))

    with open(out_c, 'w') as f:
        f.write('\n'.join(lines[:3] + pal_defs + [''] + lines[3:] + [''] + body + [''] + anim_lines) + '\n')
    with open(out_h, 'w') as f:
        f.write('\n'.join(hdr) + '\n')
    return total

def preview(sprites_list, path, scale=3):
    from PIL import Image, ImageDraw
    pad = 4
    x = y = pad
    rowh = 0
    maxw = 1200
    places = []
    for name, img, ox, oy in sprites_list:
        w, h = img.w * scale, img.h * scale
        if x + w + pad > maxw:
            x = pad
            y += rowh + pad + 10
            rowh = 0
        places.append((x, y, img, name))
        x += w + pad
        rowh = max(rowh, h)
    H = y + rowh + pad + 12
    sheet = Image.new('RGB', (maxw, H), (40, 40, 56))
    d = ImageDraw.Draw(sheet)
    for x, y, img, name in places:
        for j in range(img.h):
            for i in range(img.w):
                c = img.px[j][i]
                if c is None:
                    col = (28, 28, 40) if (i + j) & 1 else (34, 34, 48)
                else:
                    col = from565(to565(c))
                d.rectangle([x + i * scale, y + j * scale, x + i * scale + scale - 1, y + j * scale + scale - 1], fill=col)
        d.text((x, y + img.h * scale + 1), name[:14], fill=(200, 200, 220))
    sheet.save(path)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--preview', default=None)
    ap.add_argument('--scale', type=int, default=3)
    ap.add_argument('--only', default=None)
    args = ap.parse_args()

    sl, anims = sprites.build()
    root = os.path.join(os.path.dirname(__file__), '..', 'game')
    total = emit(os.path.join(root, 'assets_gen.c'), os.path.join(root, 'assets_gen.h'), sl, anims)
    print('%d sprites, %d pixel bytes' % (len(sl), total))
    if args.preview:
        sel = sl if not args.only else [s for s in sl if any(k in s[0] for k in args.only.split(','))]
        preview(sel, args.preview, args.scale)

if __name__ == '__main__':
    main()
