#!/usr/bin/env bash
#
# Build QUASAR for the Coldcard Q  ->  release/quasar-<version>-q1.dfu
#
# Same steps as the stock Coldcard build (stm32/shared.mk): MicroPython's stm32
# port with our board directory, then signit.py signs the image with key zero
# (the public developer key) and dfu.py wraps it for the microSD installer.
#
# Needs: arm-none-eabi-gcc (Arm GNU Toolchain 13), make, git,
#        python3 with ecdsa and click (pip install -r firmware/requirements.txt)
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MPY="$ROOT/external/micropython"
PORT="$MPY/ports/stm32"
BOARD=COLDCARD_Q1
BUILD="$PORT/build-$BOARD"
OUT="$ROOT/release"
PYTHON="${PYTHON:-python3}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 4)}"
VERSION="$(sed -n 's/^#define QUASAR_VERSION *"\(.*\)"/\1/p' "$ROOT/game/game.h")"

command -v arm-none-eabi-gcc >/dev/null || {
    echo "arm-none-eabi-gcc not found: install the Arm GNU Toolchain and put its bin/ on PATH" >&2
    exit 1
}
"$PYTHON" -c 'import ecdsa, click' 2>/dev/null || {
    echo "python needs ecdsa and click: pip install -r firmware/requirements.txt" >&2
    exit 1
}

echo "== sources"
git -C "$ROOT" submodule update --init external/micropython
git -C "$MPY" submodule update --init lib/stm32lib

echo "== board"
# MicroPython looks for boards/$BOARD; point it at ours (the submodule ignores it)
ln -sfn "../../../../../firmware/$BOARD" "$PORT/boards/$BOARD"

# FAT timestamps: a fixed build date instead of the RTC, like the stock build
"$PYTHON" - "$ROOT/firmware/$BOARD/file_time.c" <<'EOF'
import sys, datetime
d = datetime.date.today()
v = ((d.year - 1980) << 25) | (d.month << 21) | (d.day << 16)
open(sys.argv[1], 'w').write(
    '// AUTO-generated by build.sh on %s\n'
    '#include <stdint.h>\n\n'
    '// this overrides ports/stm32/fatfs_port.c\n'
    'uint32_t get_fattime(void) {\n    return 0x%08xUL;\n}\n' % (d, v))
EOF

echo "== mpy-cross"
# A host tool: newer host compilers warn about this MicroPython's (2020) sources,
# so build it without -Werror. The firmware itself keeps -Werror.
make -C "$MPY/mpy-cross" -j"$JOBS" CWARN="-Wall -Wextra -Wno-unused-parameter -Wpointer-arith" \
    >/dev/null 2>&1 || make -C "$MPY/mpy-cross" CWARN="-Wall"

echo "== firmware"
make -C "$PORT" BOARD=$BOARD DEBUG_BUILD=0 -j"$JOBS"

echo "== sign"
mkdir -p "$OUT"
SIGNED="$BUILD/quasar-signed.bin"
DFU="$OUT/quasar-$VERSION-q1.dfu"
( cd "$ROOT/firmware" && "$PYTHON" tools/sign.py sign "$VERSION" \
        -b "$BUILD" -m q1 --keydir keys -o "$SIGNED" )
( cd "$ROOT/firmware" && "$PYTHON" tools/sign.py check "$SIGNED" )
"$PYTHON" "$MPY/tools/dfu.py" -b 0x08020000:"$SIGNED" "$DFU"

echo
echo "Built $DFU"
( cd "$OUT" && sha256sum "$(basename "$DFU")" | tee "$(basename "$DFU").sha256" )
